
version: 2

project_name: "Slug"

builds:
  - id: "slug"
    main: "./cmd/app/"
    binary: "./bin/slug"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.BuildDate={{.Date}} -X main.Commit={{.ShortCommit}}'

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_v
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE.md
      - README.md
      - extras/*
      - lib/*
      - tests/*
      - webroot/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: "Features"
      regexp: "^feat(.*)"
    - title: "Refactor"
      regexp: "^refactor(.*)"
    - title: "Fixes"
      regexp: "^fix(.*)"

release:
  make_latest: true
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
