source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "csv"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-gist"
  gem "jekyll-include-cache"
  gem "jekyll-paginate"
  gem "jekyll-remote-theme"
  gem "jekyll-sitemap"
  gem "jemoji"
end
