name: build-and-test.yml

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.go'
      - '**.slug'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.x'

      - name: Set SLUG_HOME
        run: |
          echo "SLUG_HOME=$(pwd)" >> $GITHUB_ENV

      - name: Build and test
        run: |
          echo "Using SLUG_HOME=$SLUG_HOME"
          make test

      - name: Tag latest and build version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
          # Create annotated version tag (fails if exists)
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
      
          # Create or move 'latest' to this commit
          git tag -f -a latest -m "Latest build"
      
          # Push both tags (force for 'latest' only)
          git push origin "v${{ github.run_number }}"
          git push -f origin latest

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          distribution: goreleaser
          version: "v${{ github.run_number }}"
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
